Feature: Portfolio: details popup window
fezzopro/portfolio-mobile-first pull request #14
Opened 2023-04-12 18:28 UTC by fezzopro

## Description
This PR contains instructions from [Portfolio: details popup window](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md)

## Introduced changes

* Linter configuration files from [Microverse Linter](https://github.com/microverseinc/linters-config)  
* [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
* PR documentation best practices can be found [HERE](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
* Using JavaScript to manipulate DOM elements
* JavaScript events & event handling
* Use objects to store and access data
* Portfolio changes reflected on:
  * index.html
  * style.css
  * main.js

## Project requirements

- You should implement the following interactions:

  - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
  - When the user clicks (or taps) the close (X) button, the popup disappears.
  - In order to associate each project with the popup window details, you must refactor the project section:

- You need to use a JavaScript array to store all the information for all projects.
  - For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, and link to the source.
  - You need to update the main page to create the projects section dynamically using the information stored in that JavaScript object. Remember, the HTML in that section is created when the page loads.
  - After that, you could implement the popup window.

- You should implement popups for both mobile and desktop screen sizes:

  - ![Screenshot 2023-04-12 200939](https://user-images.githubusercontent.com/42069952/231551099-afc88f35-2845-4d35-b32a-9b78544e1d31.png)

  - ![Screenshot 2023-04-12 200854](https://user-images.githubusercontent.com/42069952/231551118-a79b37f0-5b79-42b8-a3bd-eed4b1533567.png)

You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2023-04-12 19:24 UTC, Zuhaib042 requested changes
Hi @fezzopro 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif)

## Highlights
✅ Descriptive PR
✅ Correct Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 19:24 UTC, Zuhaib042 commented on main.js
> +  },
- [ ] Kindly consider adding `link to live image` and `link to source` in all the objects of this `projectArray` as it is suggested in the requirements.
  -  For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.

2023-04-12 19:24 UTC, Zuhaib042 commented on index.html
>              <li class="year">2015</li>
- [ ] Two of the main requirements of this milestone are: 
1) to create all the projects cards dynamically 
2) Then, to build popups for each card dynamically also.
To fulfill these both requirements, we make use of the information we stored in the array of objects in JS file. Right now, you are creating popups dynamically from that array but you are not creating the projects cards dynamically so please consider removing everything inside the `<section class="work" id="work">` and create all the cards dynamically from the same array of objects.
This way adding projects in the future will be easy, all you need to do would be to add another object in that array.
-  You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
- After that, you could implement the popup window.

2023-04-12 19:24 UTC, Zuhaib042 commented on main.js
> +// const screenWidth = document.querySelector('body').style.width;
- [ ] Kindly remove this commented code as it makes our codebase unclean and it's against best practices.

2023-04-13 02:17 UTC, binhussen approved these changes
Hi @fezzopro , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 06:56 UTC, merged